name: 'Terraform'

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Output Terraform version for debugging
      - name: Terraform Version
        run: terraform version

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          cd environments/dev
          terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: |
          cd environments/dev
          terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: |
          cd environments/dev
          terraform plan -input=false

      # Apply changes according to Terraform configuration files
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: |
          cd environments/dev
          terraform apply -auto-approve -input=false
